services:
    db:
        image: postgres:15-alpine
        container_name: database_container
        restart: always
        environment:
            # automatically looks for .env files
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            DATABASE_URL: ${DATABASE_URL:-postgres://ethanpetree:hellohecker@db:5432/mydb}"
        volumes:
            # path on the right is the filepath to the data in a standard postgres container
            - db_data:/var/lib/postgresql/data
    web:
        build:
            context: ./server
            # dockerfile: ./server/Dockerfile
        image: ethanjpetree/workout-app:latest # Forces the build to use this exact name
        container_name: workout_app_container
        restart: always
        ports:
            - "3000:3000"
        # environment:
        depends_on:
            - db

volumes:
    db_data:
