// regex generated by google gemimi flash
const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-7][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const { WorkoutRepo } = require("../repositories/WorkoutRepo");
const { ExerciseRepo } = require("../repositories/ExerciseRepo");

class WorkoutService {
    static validateWorkout(workout) {
        if (workout.type && workout.length && workout.exercises) {
            return;
        } else {
            throw new Error("Workout is not valid, make sure all fields are correct");
        }
    }

    static isValidUUID(uuid) {
        return typeof uuid === "string" && UUID_REGEX.test(uuid);
    }

    static async getAllWorkouts() {
        const workouts = await WorkoutRepo.getAllWorkouts();
        return workouts;
    }

    static async getAllExercisesFromWorkout(workout_id) {
        if (!this.isValidUUID(workout_id)) throw new Error("Workout id is not valid");
    }

    static async addWorkout(type, length) {
        // 1. Baseline Validation
        if (!(type && length)) throw new Error("Type and Length must be defined");
        // 2. Logical Constraints
        // if (length && length > 15) {
        //     throw new Error("Workout length must be 15 or under.");
        // }
        // 3. Data Formatting
        const typeFormatted = type?.trim()?.toUpperCase();
        // 4. Persistence
        const rowsAffected = await WorkoutRepo.addWorkout(typeFormatted, length);

        return rowsAffected;
    }

    static async updateWorkout(workout_id, type, length) {
        // 1. Baseline Validation
        if (!this.isValidUUID(workout_id)) throw new Error("Workout id is not valid");
        if (typeof type != "string") throw new Error("Type parameter must be a string value.");
        // 2. Logical Constraints
        if (length && length > 15) {
            throw new Error("Workout length must be 15 or under.");
        }
        // 3. Data Formatting
        const typeFormatted = type?.trim()?.toUpperCase();
        // 4. Persistence
        const rowsAffected = await WorkoutRepo.updateWorkout(typeFormatted, length, workout_id);

        return rowsAffected;
    }

    static async deleteWorkout(workout_id) {
        // 1. Baseline Validation
        if (!this.isValidUUID(workout_id)) throw new Error("Workout id is not valid");
        const rowsAffected = await WorkoutRepo.deleteWorkout(workout_id);

        return rowsAffected;
    }

    static async getWorkoutById(workout_id) {
        // 1. Baseline Validation
        if (!this.isValidUUID(workout_id)) throw new Error("Workout id is not valid");
        const workoutResult = await WorkoutRepo.findWorkoutById(workout_id);

        if (workoutResult) {
            return workoutResult;
        } else {
            throw new Error("Workout by given ID does not exist");
        }
    }

    static async addExerciseToWorkout(workout_id, exercise_id, sequence_order) {
        // 1. Baseline Validation
        if (!(this.isValidUUID(workout_id) && this.isValidUUID(exercise_id))) throw new Error("Both the workout id and the exercise id must be valid");
        // 2. Logical Constraints
        //TODO: refine sequence order validation

        //promise.all fails fast as soon as one process fails, as well as runs all async processes side by side.
        const [workoutExists, exerciseExists] = await Promise.all([WorkoutRepo.exists(workout_id), ExerciseRepo.exists(exercise_id)]);
        if (!workoutExists) throw new Error("Workout does not exist");
        if (!exerciseExists) throw new Error("Exercise does not exist");

        const result = await WorkoutRepo.addExercise(workout_id, exercise_id);

        return result;
    }
    static async removeExerciseFromWorkout(workout_id, exercise_id) {
        // 1. Baseline Validation
        if (!(this.isValidUUID(workout_id) && this.isValidUUID(exercise_id))) throw new Error("Both the workout id and the exercise id must be valid");
        // 2. Logical Constraints
        //promise.all fails fast as soon as one process fails, as well as runs all async processes side by side.
        const [workoutExists, exerciseExists] = await Promise.all([WorkoutRepo.exists(workout_id), ExerciseRepo.exists(exercise_id)]);
        if (!workoutExists) throw new Error("Workout does not exist");
        if (!exerciseExists) throw new Error("Exercise does not exist");

        const result = await WorkoutRepo.removeExercise(workout_id, exercise_id);

        return result;
    }
}

module.exports = { WorkoutService };
